FROM golang:1.21-alpine AS build
WORKDIR /app
COPY go.mod ./
RUN go mod download || true
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /drone ./cmd/drone

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=build /drone .
EXPOSE 9101-9108/tcp
CMD ["./drone"]
