name: ormuz-network
version: 1.0.0

client:
  organization: OrmuzOrg1
  logging:
    level: info

channels:
  ormuz-channel:
    orderers:
      - orderer.ormuz.com
    peers:
      peer0.org1.ormuz.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  OrmuzOrg1:
    mspid: OrmuzOrg1MSP
    peers:
      - peer0.org1.ormuz.com

orderers:
  orderer.ormuz.com:
    url: localhost:7050
    tlsCACerts:
      path: ""

peers:
  peer0.org1.ormuz.com:
    url: localhost:7051
    tlsCACerts:
      path: ""